### ISSUE TITLE
Emergency Stop button not at the top

### ISSUE THREAD

**Issue by pablogventura** [ntoff/OctoPrint-Estop#1]
Emergency Stop button appears bellow file tab. I want to it appear at the top. It's a bug?

**Comment by ntoff** [comment]
No, it's not a bug. Please read the readme section on the position. By default OctoPrint puts plugins at the bottom of the standard sidebar items, you have to edit config.yaml to adjust the position. You can put it anywhere you like.

https://github.com/ntoff/OctoPrint-Estop#position

**Comment by pablogventura** [comment]
Thanks you! Now it's working! But, is a little confusing that https://github.com/ntoff/OctoPrint-Estop#position uses tabs instead spaces. Great plugin! Thanks for your work!

**Comment by ntoff** [comment]
Sorry, I'll check out the tabs v spaces thing and update the readme. I also just created an FAQ so if you have any ideas about stuff you think would help future users then please let me know.

**Comment by ntoff** [comment]
Ok, that should be the readme taken care of, thanks for pointing that out.
