### ISSUE TITLE
M112 appears to do bad things in Smoothieware

### ISSUE THREAD

**Issue by overling** [ntoff/OctoPrint-Estop#2]
I read the docs on M112 in smoothieware and it claims that M112 shuts down the heater and hot bed and disconnects the controller.

The reality of what M112 does is sends a high output on the PSU pin generally meaning it issues an M80 command and then it disconnects the controller.

So in the case of my machine... when i press emergency stop it turns on the power supplies and then disconnects the controller connection to octoprint... bad bad bad, kind of the opposite of what you want when you press E-stop.

I changed the command for E-stop to M81 so all it does it turn off the PSU pin which shuts off the power supplies.

**Comment by ntoff** [comment]
The command is user configurable for that very reason, just change it to whatever works for you. I'm not going to be doing any fancy automatic firmware detection, there are too many wild cowboys out there doing their own implementations of m/gcodes. Whatever your controller is doing, it sounds very non-standard and absolutely stupid.

![image](https://user-images.githubusercontent.com/9030085/34326508-06503b4c-e8fa-11e7-8b7a-c8c8ba41e054.png)
